/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-04-10 04:43:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.*;

public final class mainForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Animal Rescue</title><!-- 메인화면, 최초 실행시 로그인 화면으로 이동한다. 로그인 성공시 메인화면이 나타난다. -->\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery.bxslider.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.bxslider.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- JQuery ,import -->\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"hb\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/mainBody.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/mainHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"bxslider\">\r\n");
      out.write("\t\t\t<div><a href=\"#\"><img src=\"/animalRescue/img/main1.jpg\" class=\"w100\"></a></div>\r\n");
      out.write("\t\t\t<div><a href=\"#\"><img src=\"/animalRescue/img/main2.jpg\" class=\"w100\"></a></div>\r\n");
      out.write("\t\t\t<div><a href=\"#\"><img src=\"/animalRescue/img/main3.jpg\" class=\"w100\"></a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"wrap-body\">\r\n");
      out.write("\t\t\t<div class=\"wrap-list\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"notice-title bgblur\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/animalRescue/SearchList.anires\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt20\">うちの子が  <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t消えちゃった！</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p class=\"txt40\">[click!]</p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt17\">公告案内</p>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"notice1\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/animalRescue/adopt_list.anires\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt20\">買わないで<br>里親がなるのは。。</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt17\">里親申請案内</p>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"notice2\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/animalRescue/list.anires?page=1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt20\">我が子が痛くて<br>病気があります。</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt17\">病院探し</p>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"notice3\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/animalRescue/protectList.anires?page=1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt20\">痛がる<br>動物たち </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt17\">保護センターへ</p>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--공지사항 및 다른 게시판들 들어갈 창들-->\r\n");
      out.write("\t\t\t\t<div class=\"board\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"anounce\">迷子公告案内<a href=\"/animalRescue/SearchList.anires\" class=\"more\">more</a></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 
											AnimalSearch as = new AnimalSearch();
											AnimalSearchDAO dao1 = new AnimalSearchDAO();
											int ani_no1 = dao1.getNo();
											for(int i=0; i<4;i++){
												if(ani_no1!=0){
													as = dao1.viewSearch(ani_no1);
													if(as!=null) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><p>");
      out.print(as.getAni_date().toString().substring(2) );
      out.write("</p><a href=\"/animalRescue/searchView.anires?ani_no=");
      out.print(ani_no1);
      out.write("\" class=\"color-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(as.getAni_subject());
      out.write("<span class=\"new\">N</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
ani_no1--;}}} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"anounce\">里親申請案内<a href=\"/animalRescue/adopt_list.anires\" class=\"more\">more</a></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 
											Animal_adopt aa = new Animal_adopt();
											AnimalDAO dao2 = new AnimalDAO();
											int ani_no2 = dao2.Animal_adoptNumber()-1;
											for(int i=0; i<4;i++){
												if(ani_no2!=0){
													aa = dao2.adoptSelect(ani_no2);
													if(aa!=null){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><p>");
      out.print( aa.getAni_date().substring(2) );
      out.write("</p><a href=\"javascript:void(window.open('/animalRescue/adopt_select.anires?ani_no=");
      out.print(ani_no2);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(aa.getAni_subject());
      out.write("'))\" class=\"color-sub\">\r\n");
      out.write("                             \t\t\t ");
      out.print(aa.getAni_subject());
      out.write("<span class=\"new\">N</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
ani_no2--;}}} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"anounce\">サポート掲示板<a href=\"/animalRescue/supportboard.anires\" class=\"more\">more</a></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 
											Support st = new Support();
											SupportDAO dao3 = new SupportDAO();
											int ani_no3 = dao3.SupportNumber();
											System.out.println(ani_no3);
											for(int i=0; i<4;i++){
												if(ani_no3!=0){
													st = dao3.SupportSelect(ani_no3);
													if(st!=null) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>");
      out.print(st.getDate().substring(2,10) );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <a href=\"/animalRescue/supportView.anires?snum=");
      out.print(ani_no3);
      out.write("\" class=\"color-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     ");
      out.print(st.getSubject());
      out.write("<span class=\"new\">N</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										ani_no3--;
										}else break;
												}} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- \t<div class=\"w1200\"> -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/mainFooter.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- </div> -->\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
