/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-04-09 04:02:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Protect;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class protectWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta name = \"viewport\" content = \"width = device-width, initial-scale=1\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery.bxslider.css\" rel=\"stylesheet\"> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<title>登録</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.tab {\r\n");
      out.write("\t\t  float: left;\r\n");
      out.write("\t\t  border: 1px solid #ccc;\r\n");
      out.write("\t\t  background-color: #f1f1f1;\r\n");
      out.write("\t\t  width: 25%;\r\n");
      out.write("\t\t  height: 300px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.mid_content{\r\n");
      out.write("\t\t\twidth : 74.5%;\r\n");
      out.write("\t\t\tfloat : left;\r\n");
      out.write("\t\t\tmargin-left : 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.top_content{\r\n");
      out.write("\t\t\tpadding : 18px; \r\n");
      out.write("\t\t\tbackground-color : skyblue;\r\n");
      out.write("\t\t\ttext-align : center;\r\n");
      out.write("\t\t\tmargin-bottom : 3px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.tab button {\r\n");
      out.write("\t\t  display: block;\r\n");
      out.write("\t\t  background-color: inherit;\r\n");
      out.write("\t\t  color: black;\r\n");
      out.write("\t\t  padding: 22px 16px;\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t  border: none;\r\n");
      out.write("\t\t  outline: none;\r\n");
      out.write("\t\t  text-align: left;\r\n");
      out.write("\t\t  cursor: pointer;\r\n");
      out.write("\t\t  font-size: 17px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.tab button:hover {\r\n");
      out.write("  \t\t\tbackground-color: #ddd;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.tab button.active {\r\n");
      out.write("\t\t  background-color: #ccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttable.type01 {\r\n");
      out.write("\t\t    border-collapse: separate;\r\n");
      out.write("\t\t    border-spacing: 1px;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    line-height: 1.5;\r\n");
      out.write("\t\t    border-top: 1px solid #ccc;\r\n");
      out.write("\t\t    margin: 20px 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\ttd.style1 {\r\n");
      out.write("\t\t    width: 150px;\r\n");
      out.write("\t\t    padding: 10px;\r\n");
      out.write("\t\t    font-weight: bold;\r\n");
      out.write("\t\t    vertical-align: top;\r\n");
      out.write("\t\t    border-bottom: 1px solid #ccc;\r\n");
      out.write("\t\t    background: #efefef;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\ttd.style2 {\r\n");
      out.write("\t\t    width: 350px;\r\n");
      out.write("\t\t    vertical-align: top;\r\n");
      out.write("\t\t    border: 1px solid #ccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#listbutton{\r\n");
      out.write("\t\t\tfloat: right;\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\tbackground-color: inherit;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tpadding: 19px 5px;\r\n");
      out.write("\t\t\twidth: 19%;\r\n");
      out.write("\t\t\tborder: none;\r\n");
      out.write("\t\t\toutline: none;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tfont-size: 14px;\r\n");
      out.write("\t\t\tmargin-left : 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.btn_ok{\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\t   \tbackground:#426aaa; \r\n");
      out.write("\t\t\t\t   \tcolor : #fff;\r\n");
      out.write("\t\t\t\t   \twidth : 200px; \r\n");
      out.write("\t\t\t\t   \theight : 70px;\r\n");
      out.write("\t\t\t\t    border : 0 none;\r\n");
      out.write("\t\t\t\t    outline: none;\r\n");
      out.write("\t\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t\t    cursor : pointer;\r\n");
      out.write("\t\t\t\t    font-size: 14px;\r\n");
      out.write("\t\t\t\t    margin-left : 10px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"hb\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/mainBody.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/mainHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class = \"top_content\">\r\n");
      out.write("\t\t\t<h2>保護キャンペン</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class = \"tab\">\r\n");
      out.write("\t\t\t<button onclick = \"location.href='/animalRescue/list.anires?page=1'\">病院リスト</button>\r\n");
      out.write("\t\t\t\t<button onclick = \"location.href='/animalRescue/protectList.anires?page=1'\">保護センターリスト</button>\r\n");
      out.write("\t\t\t\t<button onclick=\"location.href='/animalRescue/supportboard.anires'\">サポート掲示板</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class = \"mid_content\">\r\n");
      out.write("\t\t<table style=\"text-align: center;\">\r\n");
      out.write("        \t<tr>\r\n");
      out.write("            \t<td width = \"650\">\r\n");
      out.write("                <font size=\"5em\">\r\n");
      out.write("                \t保護キャンペン情報登録\r\n");
      out.write("                </font>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        <form method=\"post\" action=\"/saveTheAnimal/protectWrite.anires?page=1\">\r\n");
      out.write("\t\t<table class=\"type01\">\r\n");
      out.write("        \t<tr>\r\n");
      out.write("            \t<td class=\"style1\">保護キャンペン名</td>\r\n");
      out.write("                <td class=\"style2\"><input type=\"text\" name=\"name\" style=\"width:170px; height:36px; border:none\"></input></td>\r\n");
      out.write("\t\t\t\t<td class=\"style1\">該当地域</td>\r\n");
      out.write("\t\t\t\t<td class=\"style2\"><input type=\"text\" name=\"area\" style=\"width:170px; height:36px; border:none\"></input></td>\r\n");
      out.write("             </tr>\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t <td class=\"style1\">住所</td>\r\n");
      out.write("\t\t\t\t <td colspan=\"4\" class=\"style2\"><input type=\"text\" name=\"adress\" size=\"55\" style=\"width:510px; height:36px; border:none\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("            \t<td class=\"style1\">電話番後</td>\r\n");
      out.write("                <td class=\"style2\"><input type=\"text\" name=\"tel\" style=\"width:170px; height:36px; border:none\"></input></td>\r\n");
      out.write("\t\t\t\t<td class=\"style1\">営業時間</td>\r\n");
      out.write("\t\t\t\t<td class=\"style2\"><input type=\"text\" name=\"open\" style=\"width:170px; height:36px; border:none\"></input></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("            \t<td class=\"style1\">病院紹介</td>\r\n");
      out.write("                <td colspan=\"3\" class=\"style2\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                <textarea rows=\"10\" cols=\"65\" name=\"content\" style=\"width:520px; height:150px; border:none\"></textarea>\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\" class=\"style1\">グーグルマップ座標</td> \r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("            \t<td class=\"style1\">Maplat</td>\r\n");
      out.write("                <td class=\"style2\"><input type=\"text\" name=\"maplat\" style=\"width:170px; height:36px; border:none\"></input></td>\r\n");
      out.write("\t\t\t\t<td class=\"style1\">Maplng</td>\r\n");
      out.write("\t\t\t\t<td class=\"style2\"><input type=\"text\" name=\"maplng\" style=\"width:170px; height:36px; border:none\"></input></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("        <div>             \r\n");
      out.write("               \t<button type=\"button\" class=\"btn_ok\" onclick=\"location.href = '/saveTheAnimal/protectList.anires?page=1'\">取り消し</button>\r\n");
      out.write("               \t<button type=\"submit\" class=\"btn_ok\" onclick=\"alert('情報が登録しました。')\">作成</button>\r\n");
      out.write("        </div>    \r\n");
      out.write("        </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/mainFooter.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
